### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by e1himself** [choodoss/cv#1]
Hi @choodoss!

I've been checking your cv website today and stumbled upon a few typos that made my eye twitching 😅

It should be `experience`, not `expirians`  :)

Please fix 'em. Thanks!

**Comment by choodoss** [comment]
I've wanted to do this several times already, but I kept forgetting. Thank you for the feedback.

**Comment by e1himself** [comment]
Still missed a couple: 

https://github.com/search?q=repo%3Achoodoss%2Fcv%20expirians&type=code

<img src=https://github.com/choodoss/cv/assets/370680/079aee06-e6a8-435c-a3b8-bc10ca9461d9 width=400>
