### ISSUE TITLE
Not great social sharing image

### ISSUE THREAD

**Issue by e1himself** [choodoss/cv#2]
The cv website is lacking a good social sharing image meta tag to make it appear nice in message apps and social networks, if shared:

![Screenshot_20230913-195102~2](https://github.com/choodoss/cv/assets/370680/99b02af4-54b4-4151-9884-be07b47bb646)

I was going to recommend wiring your photo to it, but apparently it is a sensitive topic in some countries (see https://novoresume.com/career-blog/including-photo-on-resume). Depending on your goals it may or may not be acceptable. Up to you :)

**Comment by choodoss** [comment]
Thank you for the feedback; I didn't think about that. I'll add an image – it will improve the resume.
